services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=avito
      - POSTGRES_USER=postgres
  dbgrpc:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=avito
      - POSTGRES_USER=postgres
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

#  httpserver:
#    image: http-server-image:latest
#    build:
#      context: ./golang-avito-http
#    ports:
#      - "3000:3000"
#  grpcserver:
#    image: grpc-server-image:latest
#    build:
#      context: ./golang-avito-grpc
#    ports:
#      - "8080:8080"
volumes:
  dbhttp:
  dbgrpc:
  prometheus:
  grafana-data:
#  httpserver:
#  grpcserver:

