env: "local"

database:
  host: "localhost"
  port: "5435"
  user: "postgres"
  dbname: "postgres"
  max_attempts: 5

servers:
  http:
    port: "8080"
    host: "0.0.0.0"
    timeout: 4s
    idle_timeout: 60s
  prometheus:
    port: "8081"
    host: "0.0.0.0"
    timeout: 4s
    idle_timeout: 60s
  grpc:
    grpc_pvz:
      host: "0.0.0.0"
      port: "3000"
      timeout: 5s
      insecure: false
      retries: 5
