// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/Sanchir01/golang-avito/internal/feature/user"
	mock "github.com/stretchr/testify/mock"
)

// HandlerUser is an autogenerated mock type for the HandlerUser type
type HandlerUser struct {
	mock.Mock
}

// LoginService provides a mock function with given fields: ctx, email, password
func (_m *HandlerUser) LoginService(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginService")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistrationsService provides a mock function with given fields: ctx, email, role, password
func (_m *HandlerUser) RegistrationsService(ctx context.Context, email string, role string, password string) (*user.DBUser, string, error) {
	ret := _m.Called(ctx, email, role, password)

	if len(ret) == 0 {
		panic("no return value specified for RegistrationsService")
	}

	var r0 *user.DBUser
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.DBUser, string, error)); ok {
		return rf(ctx, email, role, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *user.DBUser); ok {
		r0 = rf(ctx, email, role, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.DBUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, email, role, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, email, role, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewHandlerUser creates a new instance of HandlerUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerUser {
	mock := &HandlerUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
