basePath: /
definitions:
  api.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  user.RequestRegister:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role:
        type: string
    required:
    - email
    - password
    - role
    type: object
  user.ResponseRegister:
    properties:
      email:
        type: string
      error:
        type: string
      id:
        type: string
      role:
        type: string
      status:
        type: string
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: GitHub
    url: https://github.com/Sanchir01
  description: This is a sample server celler
  termsOfService: http://swagger.io/terms/
  title: "\U0001F680 Avito testovoe"
  version: "1.0"
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя в системе
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RequestRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseRegister'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Регистрация пользователя
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
